#!/bin/bash

echo '*** Compressing javascript ...'
java -jar /home/t0ng/data/bin/yuicompressor.jar ext/js/app.js -o ext/app.js
java -jar /home/t0ng/data/bin/yuicompressor.jar ext/js/options.js -o ext/options.js
echo Done.

echo '*** Creating zip ...'
zip -r chrome.xep.search.zip ext
echo Done.
echo Zip file is available: $(pwd)/chrome.xep.search.zip
echo
