#!/bin/bash

cd data

if [ -d xeps ]
then
	rm -r xeps
fi
mkdir xeps

if [ ! -f master ]
then
	echo Downloading master branch of XEPs
	wget http://gitorious.org/xmpp/xmpp/archive-tarball/master
fi

tar xvfz master
mv xmpp-xmpp/extensions/xep-0* xeps
rm -r xmpp-xmpp
#rm master

echo Done

